---
- name: Configures basic IPv4 connectivity.
  hosts: cisco_iol:vr-csr
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_host_key_checking: false
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Apply L3 Interface Configuration
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip }}"
        state: merged
      loop: "{{ interfaces_list }}"

    - name: Administratively enable interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            enabled: true
        state: merged
      loop: "{{ interfaces_list }}"
